name: gnn-app
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - rdkit
  - pytorch=2.3.0
  - torchvision
  - torchaudio
  - pip
  - pip:
      - streamlit
      - matplotlib
      - numpy
      - fpdf
      - requests

